services:
  front:
    image: tomyj/tp-php-front
    container_name: PHP-FINAL-front
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped